backend:
  name: github
  repo: kings591998/alshanfaricc.github.io # تأكد أن هذا هو اسم مستودعك بالضبط
  branch: master # أو main حسب فرعك الأساسي

media_folder: "assets/img" # مجلد الصور
public_folder: "/assets/img"

collections:
  - name: "settings"
    label: "إعدادات الموقع والروابط"
    delete: false
    editor:
      preview: false
    files:
      - name: "social"
        label: "روابط التواصل الاجتماعي"
        file: "data/social.yml"
        fields:
          - {label: "X (Twitter)", name: "twitter", widget: "string", required: false}
          - {label: "WhatsApp", name: "whatsapp", widget: "string", required: false}
          - {label: "Telegram", name: "telegram", widget: "string", required: false}
          - {label: "Facebook", name: "facebook", widget: "string", required: false}

  - name: "blog"
    label: "المقالات"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "صورة المقال الرئيسية", name: "image", widget: "image"}
      - {label: "المجال", name: "category", widget: "select", options: ["هندسة السرد", "هندسة الغموض", "بنية الاستثمار", "ذكاء الأعمال"]}
      - {label: "نبذة مختصرة", name: "description", widget: "text"}
      - {label: "محتوى المقال", name: "body", widget: "markdown"}
